parameters:
#    ot_nblog.example.class: OTN\blogBundle\Example

services:
#    ot_nblog.example:
#        class: %ot_nblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
